### ISSUE TITLE
`drawing.container` padx, pady and cornerradius are not functional

### ISSUE THREAD

**Issue by SidaChen1999** [cdelker/schemdraw#32]
From the source code, I found that the initializing parameters `padx`, `pady` and `cornerradius` are never used. However, the `get_bbox` function used the padding parameters from `self.params['padx']`. I'm not sure where this dictionary comes from but changing the initializer to the following works for me.
```
def __init__(self,
                   drawing: Union['Drawing', 'Container'],
                   cornerradius: Optional[float] = None,
                   padx: Optional[float] = None,
                   pady: Optional[float] = None):
        super().__init__()
        self.drawing = drawing
        self.elements: list[Element] = []
        self.params['padx'] = padx
        self.params['pady'] = pady
        self.params['cornerradius'] = cornerradius
```

**Comment by cdelker** [comment]
How are you creating and using the container? The parameters work as expected when used [in this example](https://schemdraw.readthedocs.io/en/stable/elements/flow.html#containers).

The three parameters are automatically added to `Element.params` on instantiation so the lines you added are unnecessary, and in general setting params in an __init__ is not advisable because it's a ChainMap and may mess up the prioritization/inheritance of these values. It could be you're doing something unexpected to instantiate the Container which bypasses adding them in.

**Comment by SidaChen1999** [comment]
Hi cdelker,

I used it as following:

```
with schemdraw.Drawing(unit=1) as d:
    flow.Start().label('Start')
    flow.Arrow().down().length(1.5)
    with d.container(padx=3) as c:
        flow.Box().label('Step 1').drop('E')
        flow.Arrow().right()
        flow.Box().label('Step 2')
        c.color('red')
        c.label('Subprocess', loc='N', halign='center', valign='top')
    flow.Arrow().right()
    flow.Start().label('End').anchor('W')
```

**Comment by SidaChen1999** [comment]
closed by accident

**Comment by SidaChen1999** [comment]
closed by accident

**Comment by cdelker** [comment]
Looks to be working as expected. What are you getting compared with what you're expecting? Note the container will not change the position of its contents, it just draws a box around them.

![image](https://github.com/cdelker/schemdraw/assets/44102190/58a5a794-528b-4e5a-b84c-61f1a1e64ef5)

**Comment by SidaChen1999** [comment]
emmm, looks like maybe it's the environment issue
![image](https://github.com/cdelker/schemdraw/assets/43180603/39ae3baa-e395-4ccb-acbc-f22324753481)
